# Generated by Django 3.2.6 on 2025-06-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0002_venueevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueevent',
            name='begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='venueevent',
            name='end',
            field=models.DateTimeField(),
        ),
    ]
