# Generated by Django 3.2.6 on 2025-06-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0003_auto_20250606_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorrecord',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
