# Generated by Django 3.2.6 on 2025-06-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0005_alter_sensorrecord_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueevent',
            name='description',
        ),
    ]
