# Generated by Django 3.2.6 on 2025-06-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0006_remove_venueevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueevent',
            name='event',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venueevent',
            name='instructor',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
