# Generated by Django 3.2.6 on 2025-06-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0007_auto_20250611_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorrecord',
            name='light',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
