# Generated by Django 3.2.6 on 2025-06-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0008_alter_sensorrecord_light'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueevent',
            name='title',
        ),
    ]
