# Generated by Django 3.2.6 on 2025-06-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0010_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
