# Generated by Django 3.2.6 on 2025-06-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0011_alter_alert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='loc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='node_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
