# Generated by Django 3.2.6 on 2025-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.TextField()),
                ('loc', models.TextField()),
                ('temp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hum', models.DecimalField(decimal_places=1, max_digits=3)),
                ('light', models.IntegerField()),
                ('snd', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
