# Generated by Django 3.2.6 on 2025-06-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.TextField()),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
