# Generated by Django 3.2.6 on 2025-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0004_alter_sensorrecord_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorrecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
